### ISSUE TITLE
Map relationships between apps, repos, and azure resources.

### ISSUE THREAD

**Issue by mikefab** [unicef/magicbox#15]

**Comment by jflory7** [comment]
@mikefab Anything you need my help with on this one?

**Comment by mikefab** [comment]
@jflory7 is there an appropriate place to store this map on the repo that would be private to the team?

**Comment by jflory7** [comment]
@mikefab Not a private place here. We could create a private repo to do this or find somewhere internal to host documents like this, so long as it's easy to find again.

**Comment by jflory7** [comment]
@mikefab Do we still need to follow up on this or can we close this issue?

**Comment by mikefab** [comment]
Let's keep this open another week while I think about it. Thanks for your patience.

**Comment by jflory7** [comment]
Related to #30
