### ISSUE TITLE
Create production/staging/dev deployment slots for Mobility Mapping

### ISSUE THREAD

**Issue by mikefab** [unicef/magicbox#19]

**Comment by jflory7** [comment]
@carloscdias @mikefab I think this is done now, right?

**Comment by carloscdias** [comment]
@jflory7 Yes, it is.

We can access them at:

https://magicbox-maps.azurewebsites.net/
https://magicbox-maps-staging.azurewebsites.net/
https://magicbox-maps-development.azurewebsites.net/

**Comment by jflory7** [comment]
@carloscdias Woot, awesome! Closing this as complete then.
